#!/bin/bash
# can be used to increase or decrease screen brightness by passing either - or + as argument

file="/sys/class/backlight/intel_backlight/brightness"
level=$(cat $file)

if [[ "$#" -eq 0 ]]; then
    cat $file
elif [[ "$1" = "-" ]]; then
    echo $(( level - 25 )) > $file
elif [[ "$1" = "+" ]]; then
    echo $(( level + 25 )) > $file
fi
