#!/bin/bash
# i use this to turn on and off my webcam,
# to save laptop battery.

case "$1" in
  on)
    sudo modprobe uvcvideo
    ;;
  off)
    sudo modprobe -r uvcvideo 
    sudo modprobe -r videodev
    ;;
esac
