#!/bin/bash

if [ ! -x /usr/bin/cmus-remote ];
then
notify-send "cmus is not installed."
exit
fi

FILE=$( cmus-remote -Q 2>/dev/null | grep "file" | sed 's/^file //g' )
ARTIST=$( cmus-remote -Q 2>/dev/null | grep " artist " | sed s/tag\ artist/Artist\:/g )
ALBUM=$( cmus-remote -Q 2>/dev/null | grep " album " | sed s/tag\ album/Album\:/g )
TITLE=$( cmus-remote -Q 2>/dev/null | grep " title " | sed s/tag\ title/Song\:/g )

ffmpeg -y -i "$FILE" "/tmp/cover.png"

if [ -z "$ARTIST" ];
then
notify-send "Nothing"
else
notify-send -i /tmp/cover.png "$ARTIST 
$TITLE 
$ALBUM"
fi

